// Camada didática separada da SUS-BA 2026.2. Não altera enunciados, alternativas ou gabaritos.
const SUS262_LESSON_EXTRA={
1:"Os critérios de Duke organizam a probabilidade de endocardite. Critérios maiores dependem principalmente de microbiologia típica persistente e evidência de acometimento endocárdico; critérios menores incluem predisposição, febre e fenômenos vasculares/imunológicos. Nódulos de Osler são dolorosos e entram como fenômeno imunológico. Aqui, não transforme suspeita em critério maior que o enunciado não forneceu.",
2:"Endocardite do lado direito é particularmente lembrada em usuários de drogas injetáveis, porque microrganismos inoculados na circulação venosa chegam primeiro à valva tricúspide. O agente clássico é Staphylococcus aureus. Associação de prova: droga IV → tricúspide → S. aureus.",
3:"Na endocardite, cirurgia pode ser necessária por três grandes motivos: insuficiência cardíaca por destruição valvar, infecção não controlada e prevenção de embolização em situações selecionadas. Insuficiência cardíaca grave/refratária causada pela lesão valvar é uma das indicações mais fortes e urgentes.",
4:"A dor inflamatória axial melhora com movimento, piora no repouso, pode despertar na segunda metade da noite e acompanha rigidez matinal. Sacroileíte bilateral reforça espondiloartrite axial. HLA-B27 é marcador de associação e apoio diagnóstico, não um teste que sozinho cria o diagnóstico. Mnemônico: inflamatória 'enferruja parada e destrava andando'.",
5:"O tratamento inicial da espondiloartrite axial combina exercício/fisioterapia com AINE quando não contraindicado. A atividade física preserva mobilidade e postura; o AINE controla dor e inflamação. Terapia biológica é escalonamento para doença ativa apesar da abordagem inicial adequada.",
6:"A manifestação extra-articular clássica é uveíte anterior aguda: olho vermelho, doloroso, fotofobia e visão borrada. Pense no eixo espondiloartrite–olho. Psoríase e doença inflamatória intestinal pertencem à família das espondiloartrites, mas a pergunta pede a associação clássica do quadro.",
7:"Deficiência de B12 prejudica síntese de DNA, produzindo megaloblastose: macrócitos/ovalócitos e neutrófilos hipersegmentados são pistas clássicas. Quando a prova mistura anemia com parestesias e dificuldade de marcha, B12 sobe ainda mais no ranking porque, ao contrário do folato, pode causar síndrome neurológica.",
8:"Déficit grave de B12 com manifestações neurológicas merece reposição rápida e confiável; por isso a via parenteral é a escolha clássica no cenário. Corrigir só a dieta é lento e pode não resolver causas de má absorção. Não espere a anemia ficar dramática para proteger o sistema nervoso.",
9:"A B12 participa do metabolismo do metilmalonil-CoA. Quando falta, aumenta ácido metilmalônico e ocorre dano à mielina, podendo atingir colunas posteriores e tratos corticoespinais: a degeneração combinada subaguda. Associação: B12 baixa → 'fio elétrico sem isolamento' → parestesias, perda vibratória e alteração de marcha.",
10:"História familiar muda o relógio do rastreamento. Quando um parente de primeiro grau teve câncer colorretal jovem, o rastreio começa mais cedo e com colonoscopia. Regra de prova desta questão: aos 40 anos ou 10 anos antes da idade do diagnóstico do familiar, escolhendo o que vier primeiro, com intervalos menores de seguimento.",
11:"Com válvula ileocecal competente, o conteúdo não consegue descomprimir para o intestino delgado: forma-se uma obstrução em alça fechada. Pela lei de Laplace, o segmento de maior raio sofre maior tensão de parede; por isso o ceco é especialmente vulnerável a isquemia e perfuração. Imagine um balão preso nas duas pontas.",
12:"No pós-operatório de anastomose intestinal, febre, taquicardia, leucocitose e dor abdominal por volta do 5º–7º dia devem acender a luz para deiscência/fístula anastomótica, mesmo sem abdome rigidamente peritonítico. A investigação inicial depende da estabilidade, frequentemente com TC contrastada; instabilidade ou peritonite muda a urgência cirúrgica.",
13:"A cicatrização tem fases. Na fase proliferativa, fibroblastos migram, produzem matriz extracelular e inicialmente predominam fibras de colágeno tipo III; depois, no remodelamento, há substituição progressiva por colágeno tipo I e aumento da resistência tênsil. Mnemônico: primeiro III, depois I.",
14:"Hipoalbuminemia funciona como marcador de reserva nutricional/doença sistêmica e se associa fortemente a complicações de ferida. Diabetes, insuficiência renal e outros fatores também atrapalham, mas a questão pede a associação independente mais robusta presente no caso. Albumina baixa = sinal de alerta para cicatrização.",
15:"Uma ferida com bordas desvitalizadas e pouco tecido de granulação precisa de preparo do leito e correção dos fatores sistêmicos antes de um fechamento definitivo. Terapia por pressão negativa pode favorecer controle de exsudato e granulação em casos selecionados; suporte nutricional é parte do tratamento. Fechar cedo um leito ruim é 'pintar parede úmida'.",
16:"O pH urinário ajuda a adivinhar o cristal. Ácido úrico é pouco solúvel em urina ácida; portanto pH 4,5 é uma pista forte. Estruvita costuma acompanhar infecção por bactérias produtoras de urease e urina alcalina. Associação: ácido úrico gosta de ambiente ácido.",
17:"Tamanho, localização, obstrução, infecção, função renal e controle da dor guiam a conduta. Um cálculo ureteral proximal de 11 mm tem baixa chance de eliminação espontânea; somado a hidronefrose e dor recorrente, favorece tratamento intervencionista. Se houvesse obstrução infectada, drenagem urgente seria prioridade.",
18:"Para cálculos de ácido úrico, uma estratégia central é aumentar a solubilidade do urato alcalinizando a urina, além de hidratação e medidas dietéticas/metabólicas apropriadas. O objetivo é mudar o 'ambiente químico' que permitiu o cristal. Tiazídico lembra mais prevenção de cálcio em hipercalciúria.",
19:"NIC 1 corresponde a lesão escamosa de baixo grau e, especialmente em jovem imunocompetente, apresenta alta taxa de regressão espontânea. Por isso a lógica é vigilância conforme protocolo, não retirar um pedaço do colo imediatamente. Excisão desnecessária traz morbidade cervical e obstétrica.",
20:"HPV de baixo risco evolutivo e resposta imune explicam por que muitas NIC 1 regridem. O ponto da questão é proporcionalidade: lesão de baixo grau não deve receber tratamento de alto impacto sem indicação. Pense 'baixo grau = alta chance de voltar atrás'.",
21:"Vacina contra HPV é prevenção primária e não trata uma infecção já adquirida, mas ainda pode proteger contra outros tipos vacinais aos quais a pessoa não foi exposta. Rastreamento do colo é prevenção secundária e continua seguindo as recomendações mesmo em pessoas vacinadas. Vacina e rastreio são parceiros, não substitutos.",
22:"Nódulo endurecido, irregular, fixo, com retração cutânea e linfonodo axilar é altamente suspeito. A investigação combina imagem apropriada à idade/contexto com diagnóstico tecidual; core biopsy fornece arquitetura histológica e permite caracterização do tumor. Não trate como infecção quando não há quadro infeccioso.",
23:"Malignidade tende a infiltrar e tracionar estruturas, produzindo fixação aos planos profundos e retração de pele/mamilo. Consistência pétrea e contornos irregulares aumentam a suspeita. Dor ou ausência dela, sozinhas, discriminam muito menos.",
24:"Linfonodo axilar morfologicamente suspeito deve ser amostrado por punção aspirativa ou core biopsy, conforme cenário, antes de definir a estratégia axilar. O princípio é simples: imagem suspeita gera hipótese; citologia/histologia confirma. Não pule diretamente para esvaziamento axilar.",
25:"Mastite lactacional costuma surgir por estase de leite e trauma mamilar, facilitando inflamação e infecção. Febre, calafrios, dor e eritema localizado em cunha são clássicos. Ausência de massa flutuante fala contra abscesso naquele momento. Mnemônico: fissura + febre + faixa vermelha = mastite.",
26:"Esvaziamento eficaz da mama é tratamento, não inimigo. Corrigir a pega, manter amamentação/ordenha quando possível, analgesia e antibiótico apropriado quando indicado combatem estase e infecção. Suspender aleitamento sem necessidade tende a piorar a estase.",
27:"Se uma mastite tratada adequadamente continua com febre e dor após 48–72 horas, procure complicação, especialmente abscesso. Ultrassom é excelente para identificar coleção e guiar drenagem. A sequência mental é: não melhorou → não troque tudo às cegas → procure pus.",
28:"O detalhe 'antitérmico administrado por diferentes cuidadores' é uma pista de erro cumulativo de dose. Paracetamol em excesso produz metabólito tóxico NAPQI; quando a glutationa se esgota, surge lesão hepática. Crianças podem receber doses repetidas inadvertidamente quando ninguém soma o total diário.",
29:"N-acetilcisteína repõe precursores de glutationa e ajuda a neutralizar NAPQI. Quanto mais cedo for iniciada quando indicada, melhor. Associação: paraCETAMOL → a 'NAC' vem resgatar a glutationa. O manejo também depende da cronologia e do tipo de exposição.",
30:"Antes de qualquer nomograma ou decisão de antídoto, reconstrua a exposição: produto/concentração, dose por tomada, número de tomadas, horário e peso da criança. Em ingestão repetida, a história de dose acumulada é especialmente importante. Intoxicação é matemática clínica.",
31:"Giardia adere ao intestino delgado e prejudica absorção, levando a distensão, dor, fezes volumosas/fétidas e impacto ponderal. Não é preciso imaginar invasão profunda: o problema é a superfície absortiva funcionando mal. Pense em Giardia como 'tapete sobre as vilosidades'.",
32:"Giardíase e doença celíaca podem compartilhar distensão, diarreia/má absorção e baixo ganho ponderal. A exposição epidemiológica ajuda a separar: água não tratada, creches e surtos favorecem Giardia. História é um exame barato e poderoso.",
33:"Má absorção persistente durante uma fase de rápido crescimento pode causar deficiências de macro e micronutrientes e repercutir em crescimento e desenvolvimento. O protozoário não precisa atacar diretamente o cérebro; basta privar o organismo em desenvolvimento dos nutrientes de que precisa.",
34:"Ausência típica parece um 'pause' de poucos segundos: interrupção súbita, olhar parado, episódios frequentes e retorno imediato ao que estava fazendo, sem período pós-ictal. Isso diferencia de muitas crises focais com alteração da consciência, que podem durar mais e deixar confusão.",
35:"A assinatura clássica no EEG da ausência típica é complexo espícula-onda generalizado a 3 Hz. É uma decoreba de prova muito rentável: AUSÊNCIA = 3 Hz. Frequências mais lentas sugerem ausências atípicas em outros contextos.",
36:"Etossuximida é primeira escolha clássica quando há crises de ausência típicas isoladas. Ela atua principalmente em canais de cálcio tipo T talâmicos. Mnemônico: 'ETÔ ausente' → ETOSSUXIMIDA. Se coexistirem outros tipos de crise, a escolha pode mudar.",
37:"Na APS, o primeiro objetivo com um adolescente resistente é construir vínculo e preservar uma porta de entrada segura. Sem risco imediato, coerção costuma afastá-lo. Autonomia progressiva e confidencialidade são ferramentas de cuidado, mantendo avaliação de segurança sempre ativa.",
38:"HEEADSSS organiza uma entrevista psicossocial ampla: Home, Education/Employment, Eating, Activities, Drugs, Sexuality, Suicide/depression e Safety. É um mapa para não esquecer áreas importantes. CRAFFT é muito útil, mas é focado especificamente em álcool e outras drogas.",
39:"O cérebro adolescente ainda está em desenvolvimento. Uso frequente de cannabis se associa a prejuízos em atenção, memória/aprendizagem e a maior risco de transtornos psicóticos em pessoas vulneráveis, com relação influenciada por dose, frequência e predisposição. A orientação deve ser factual, sem moralização.",
40:"Avaliação multidimensional não é só listar doenças. Katz mede atividades básicas de vida diária; Lawton avalia atividades instrumentais; Timed Up and Go observa mobilidade e risco de quedas. Juntos ajudam a responder 'o que esta pessoa consegue fazer com segurança?', pergunta central na geriatria.",
41:"Conferência familiar é uma ferramenta clínica para alinhar informações, ouvir valores, explicitar conflitos e construir responsabilidades compartilhadas. Sempre que possível, a própria paciente participa das decisões. O profissional facilita a negociação; não atua como juiz escolhendo um filho para mandar.",
42:"Quando o problema ultrapassa saúde e envolve renda, proteção e suporte social, entra a intersetorialidade. O CRAS é porta importante da proteção social básica e pode avaliar benefícios e serviços do território. A ideia é conectar redes em vez de medicalizar uma vulnerabilidade social.",
43:"Cuidados paliativos devem entrar pela necessidade, não apenas nos últimos dias de vida. Doença avançada, sintomas importantes, perda funcional e internações repetidas são sinais de que um plano paliativo pode caminhar junto ao tratamento da doença. DPOC grave é exemplo clássico de condição não oncológica com grande carga de sofrimento.",
44:"A APS continua coordenando o cuidado mesmo quando especialistas, SAD ou hospital participam. Projeto Terapêutico Singular organiza necessidades, metas e responsabilidades; matriciamento oferece suporte especializado sem retirar o caso da equipe de referência. Pense: APS segura o mapa da viagem.",
45:"Internação paliativa deve ter um objetivo clínico que o domicílio não consegue alcançar, como controle de sintoma verdadeiramente refratário. Sobrecarga familiar é séria e exige suporte, mas não deve ser confundida automaticamente com indicação clínica hospitalar. A pergunta-chave é: existe necessidade de controle avançado indisponível em casa?"
};
function expandSUS262Lessons(){
 for(const q of SUS262){
  const raw=SUS262_RAW.find(r=>r[0]===q.number), extra=SUS262_LESSON_EXTRA[q.number];
  if(!raw||!extra)continue;
  const L='ABCD'[q.correctIndex];
  q.resolution=`<h3>📚 Mini-aula — ${q.topic}</h3><p><b>O que a questão está te contando?</b> ${raw[6]}</p><p><b>🧠 O que você precisava saber:</b> ${extra}</p><p><b>🔎 Por que as outras não são a melhor resposta?</b> ${raw[7]}</p><p><b>✅ Gabarito oficial: ${L}.</b></p><p><b>💡 Leve para a prova:</b> ${raw[6]}</p>`;
 }
}
expandSUS262Lessons();
